# Generated by Django 4.2.3 on 2023-07-18 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('task_name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('priority', models.CharField(max_length=6)),
                ('dueDate', models.DateField()),
                ('tag', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=15)),
            ],
        ),
    ]
